---
- hosts: localhost
  vars:
    # Default number of worker nodes (can be overridden via -e "worker_count=<n>")
    worker_count: "{{ worker_count | default(3) | int }}"

  tasks:
    - name: Check and delete existing master and worker nodes
      shell: |
        multipass list | awk 'NR>1 {print $1}' | while read name; do
          if [[ "$name" == "k3s-master" || "$name" =~ k3s-worker.* ]]; then
            multipass delete "$name"
          fi
        done
        multipass purge
      ignore_errors: true

    - name: Provision master node (k3s-master)
      shell: |
        multipass launch --name k3s-master --cpus 2 --memory 4G --disk 20G
      register: master_provision

    - name: Provision worker nodes dynamically
      loop: "{{ range(1, worker_count + 1) | list }}"
      shell: |
        multipass launch --name k3s-worker-{{ '%02d' | format(item) }} --cpus 1 --memory 1G --disk 4G
      register: worker_provision

    - name: Wait for all instances to be ready
      shell: multipass list
      register: instances
      until: instances.stdout.find('Running') != -1
      retries: 10
      delay: 5

    - name: Get the master node IP
      shell: multipass info k3s-master | grep IPv4 | awk '{print $2}'
      register: master_ip
      changed_when: false

    - name: Install k3s on the master node
      shell: |
        multipass exec k3s-master -- bash -c "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='--write-kubeconfig-mode 644 --disable traefik --disable-network-policy --disable servicelb' sh -"

    - name: Get K3s master token
      shell: multipass exec k3s-master -- sudo cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      changed_when: false

    - name: Install k3s agent on worker nodes
      loop: "{{ range(1, worker_count + 1) | list }}"
      shell: |
        multipass exec k3s-worker-{{ '%02d' | format(item) }} -- bash -c "curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip.stdout }}:6443 K3S_TOKEN={{ k3s_token.stdout }} sh -"

    - name: Verify nodes are added to the K3s cluster
      shell: multipass exec k3s-master -- kubectl get nodes
      register: nodes_status

    - name: Display K3s cluster nodes
      debug:
        msg: "{{ nodes_status.stdout }}"

    - name: Retrieve kubeconfig from k3s-master
      shell: multipass exec k3s-master -- sudo cat /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_output

    - name: Ensure ~/.kube directory exists
      file:
        path: ~/.kube
        state: directory
        mode: '0700'

    - name: Write kubeconfig to ~/.kube/config
      copy:
        content: "{{ kubeconfig_output.stdout }}"
        dest: ~/.kube/config
        mode: '0600'

    - name: Update kubeconfig server entry with master IP
      lineinfile:
        path: ~/.kube/config
        regexp: '^(\s*server:\s*)https://.*'
        line: "    server: https://{{ master_ip.stdout }}:6443"
        backup: yes
