name: Provision K3s Cluster

on:
  workflow_dispatch:
    inputs:
      worker_count:
        description: "Number of worker nodes to deploy"
        required: true
        default: "3"

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python and Ansible
        run: |
          sudo apt update -y
          sudo apt install -y python3 python3-pip
          pip3 install ansible

      - name: Verify Ansible installation
        run: ansible --version

      - name: Run Ansible Playbook
        run: ansible-playbook ansible/provision-k3s.yml -e "worker_count=${{ github.event.inputs.worker_count }}"
